//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAC白名单小工具.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAC白名单小工具.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///  &lt;Triggers /&gt;
        ///  &lt;Principals&gt;
        ///    &lt;Principal id=&quot;Author&quot;&gt;
        ///      &lt;LogonType&gt;InteractiveToken&lt;/LogonType&gt;
        ///      &lt;RunLevel&gt;HighestAvailable&lt;/RunLevel&gt;
        ///    &lt;/Principal&gt;
        ///  &lt;/Principals&gt;
        ///  &lt;Settings&gt;
        ///    &lt;MultipleInstancesPolicy&gt;Parallel&lt;/MultipleInstancesPolicy&gt;
        ///    &lt;DisallowStartIfOnBatteries&gt;false&lt;/DisallowStartIfOnBatteries&gt;
        ///    &lt;StopIfGoingOnBatteries&gt;false&lt;/StopIfGoingOnBatt [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string XML_前 {
            get {
                return ResourceManager.GetString("XML_前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     &lt;/Exec&gt;
        ///  &lt;/Actions&gt;
        ///&lt;/Task&gt; 的本地化字符串。
        /// </summary>
        internal static string XML_后 {
            get {
                return ResourceManager.GetString("XML_后", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       &lt;Arguments&gt; 的本地化字符串。
        /// </summary>
        internal static string XML_启动参数_前 {
            get {
                return ResourceManager.GetString("XML_启动参数_前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/Arguments&gt; 的本地化字符串。
        /// </summary>
        internal static string XML_启动参数_后 {
            get {
                return ResourceManager.GetString("XML_启动参数_后", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       &lt;Command&gt;&quot; 的本地化字符串。
        /// </summary>
        internal static string XML_程序位置_前 {
            get {
                return ResourceManager.GetString("XML_程序位置_前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;&lt;/Command&gt; 的本地化字符串。
        /// </summary>
        internal static string XML_程序位置_后 {
            get {
                return ResourceManager.GetString("XML_程序位置_后", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       &lt;WorkingDirectory&gt; 的本地化字符串。
        /// </summary>
        internal static string XML_起始位置_前 {
            get {
                return ResourceManager.GetString("XML_起始位置_前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/WorkingDirectory&gt; 的本地化字符串。
        /// </summary>
        internal static string XML_起始位置_后 {
            get {
                return ResourceManager.GetString("XML_起始位置_后", resourceCulture);
            }
        }
    }
}
